# Use root/example as user/password credentials
version: '3.1'

services:

  redis:
    image: redis
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always

  goweb:
    image: wechat-dev:1.0
    restart: always
    ports:
      - 8080:8080
    environment:
      REDIS-HOST: redis